# docker-compose --env-file docker-compose.dev.env up -d

services:
  spring-api-gateway-devonly:
    container_name: gateway-dev-service
    image: ${KCR_HOST}/mcp-hub-backend-dev/spring-api-gateway-devonly:latest
    ports:
      - 80:8000
    networks:
      - mm_dev_network

  mcp-hub-member:
    container_name: mcp-hub-member
    image: ${KCR_HOST}/mcp-hub-backend-dev/mcp-hub-member:latest
    ports:
      - 811:8081
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - mm_dev_network

  mcp-hub-workspace:
    container_name: mcp-hub-workspace
    image: ${KCR_HOST}/mcp-hub-backend-dev/mcp-hub-workspace:latest
    ports:
      - 812:8081
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - mm_dev_network

  mcp-hub-mcp:
    container_name: mcp-hub-mcp
    image: ${KCR_HOST}/mcp-hub-backend-dev/mcp-hub-mcp:latest
    ports:
      - 813:8081
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - mm_dev_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mm_dev_network

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3360:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mm_dev_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    networks:
      - mm_dev_network
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - mm_dev_network
    restart: always

networks:
  mm_dev_network:
    name: mm_dev_network
    driver: bridge
    internal: false
