server:
  port: 8000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /v3/api-docs/aggregate


spring:
  config:
    activate:
      on-profile: default
  application:
    name: apigateway-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        prefetch: 5
#  springdoc:
#    swagger-ui:
#      urls:
#        - name: member-service
#          url: /member/v3/api-docs
#        - name: mcp-service
#          url: /mcp/v3/api-docs
#        - name: workspace-service
#          url: /workspace/v3/api-docs
  cloud:
    gateway:
      httpclient:
        connect-timeout: 180000       # 연결 타임아웃 (밀리초 단위 → 180초)
        response-timeout: 180s        # 응답 타임아웃 (초 단위 → 180초)
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: http://mcp-hub-member:8080 # 컨테이너명이 꼭 member여야 함, 내부 포트가 꼭 8081이어야 함
          predicates:
            - Path=/members/**

        - id: mcp-service
          uri: http://mcp-hub-mcp:8080 # 컨테이너명이 꼭 mcp여야 함, 내부 포트가 꼭 8081이어야 함
          predicates:
            - Path=/mcps/**

        - id: workspace-service
          uri: http://mcp-hub-workspace:8080 # 컨테이너명이 꼭 workspace여야 함, 내부 포트가 꼭 8081이어야 함
          predicates:
            - Path=/workspaces/**

      globalcors:
        corsConfigurations:
          '[/**]':   # 모든 경로에 적용
            allowedOrigins: "https://8lowup-mcp-hub.vercel.app"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

#token:
#  secret: user_token

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
