name: MCP Hub API Gateway service - Develop Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃 (서브 묘듈 포함)
      - name: Checkout Code (with submodules)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      # 서브모듈도 함께 체크아웃

      # Java 17 세팅 (spring boot 빌드용)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew clean build -x test

      # Kakao Container Registry 로그인
      - name: Login to KCR
        run: echo "${{ secrets.KCR_PASSWORD }}" | docker login ${{ secrets.KCR_HOST }} -u ${{ secrets.KCR_USER }} --password-stdin

      # Docker 이미지 빌드 & KCR 푸시
      # github.event.repository.name을 통해 각 레포지토리 이름을 이미지 이름으로 사용
      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.KCR_HOST }}/mcp-hub-backend-dev/${{ github.event.repository.name }}
          TAG=${{ github.sha }}

          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

  # 게이트웨이 레포 Reusable Workflow 호출
  trigger-gateway-deploy:
    uses: 8LOWUP/spring-api-gateway-devonly/.github/workflows/mcp-market-reusable-dev.yml@main
    with:
      service: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      KCR_HOST: ${{ secrets.KCR_HOST }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
    needs: build-and-deploy