name: MCP Hub gateway service - Self Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Login to KCR
        run: echo "${{ secrets.KCR_PASSWORD }}" | docker login ${{ secrets.KCR_HOST }} -u ${{ secrets.KCR_USER }} --password-stdin

      # Docker 이미지 빌드 & KCR 푸시
      # github.event.repository.name을 통해 각 레포지토리 이름을 이미지 이름으로 사용
      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.KCR_HOST }}/project/${{ github.event.repository.name }}
          TAG=${{ github.sha }}

          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

      # 다른 서비스처럼 게이트웨이 레포 Reusable Workflow 호출
      - name: Trigger Gateway Deploy Workflow
        uses: 8LOWUP/spring-api-gateway-devonly/.github/workflows/deploy.yml@main
        with:
          service: ${{ github.event.repository.name }}
          ag: ${{ github.sha }}
