name: MCP Hub DEV Reusable Workflows - Develop Deploy

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      KCR_HOST:
        required: true
      EC2_HOST:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # SSH 키 등록 (GitHub Secrets → SSH_PRIVATE_KEY)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Dev Server
        run: |
          SERVICE=${{ inputs.service }}
          TAG=${{ inputs.tag }}
          IMAGE=${{ secrets.KCR_HOST }}/mcp-hub-backend-dev/$SERVICE:$TAG

          echo "Re-deploying $SERVICE:$TAG (clean run)"

          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd /app/compose &&
            echo 'Stopping and removing old container...' &&
            docker-compose rm -sf \$SERVICE || true &&

            echo 'Removing old image...' &&
            docker rmi -f \$IMAGE || true &&

            echo 'Pulling new image...' &&
            KCR_HOST=${{ secrets.KCR_HOST }} docker-compose --env-file docker-compose.dev.env pull \$SERVICE &&

            echo 'Starting new container...' &&
            KCR_HOST=${{ secrets.KCR_HOST }} docker-compose --env-file docker-compose.dev.env up -d --no-deps \$SERVICE
          "
      
